apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: collectstatic
          image: pshar10/todo-app:latest
          command:
            - "python"
            - "manage.py"
            - "collectstatic"
            - "--noinput"
          volumeMounts:
            - name: static-storage
              mountPath: /static
      containers:
      - name: todo
        image: pshar10/todo-app:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: sqlite-storage
          mountPath: /db.sqlite3
      volumes:
      - name: sqlite-storage
        persistentVolumeClaim:
          claimName: sqlite-pvc
