# Generated by Django 5.1.3 on 2025-01-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0008_auto_20191202_0809"),
    ]

    operations = [
        migrations.RemoveField(model_name="todo", name="update_at",),
        migrations.AddField(
            model_name="todo",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="low",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="todo", name="title", field=models.CharField(max_length=200),
        ),
    ]
